First layout test
wolox-training/da-react pull request #1
Opened 2018-10-04 20:07 UTC by Dorian30

## Summary
- I built the 4 components for the layout site and put them together.

## Screenshot
![layout](https://user-images.githubusercontent.com/36488701/46499745-3f70b280-c7f7-11e8-9f69-2645812c3f65.png)

## Trello Card
https://trello.com/c/Akp0W85v/11-setup-del-proyecto

2018-10-04 20:18 UTC, CarlosHWolox approved these changes

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/.vscode/settings.json
> +{
You shouls ignore this file aswell as it is custom for your editor

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/index.html
> +    <meta charset="UTF-8">
We use two spaces for indentation

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/index.html
> +</html>
We leave an empty line at the end of file so this icon does not show

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/scss/navbar.scss
> +  height: 90px;
This height is defined as a constant on the training. Use it as a variable

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/scss/styles.scss
> +
No empty line

2018-10-04 20:18 UTC, CarlosHWolox commented on maquetado/scss/tech.scss
> +
no empty lines.

2018-10-05 12:42 UTC, CarlosHWolox reviewed
There should not appear the application.css.map

2018-10-05 12:42 UTC, CarlosHWolox commented on maquetado/.gitignore
> +.DS_Store
Leave an empty line at end of file

2018-10-05 12:42 UTC, CarlosHWolox commented on maquetado/application.css
> +* {
This file should be added to the .gitignore

2018-10-05 12:42 UTC, CarlosHWolox commented on maquetado/scss/colors.scss
> +$grey: #C4C4C4;
leave a empty line at end of all files

2018-10-05 18:25 UTC, CarlosHWolox approved these changes

2018-10-05 23:26 UTC, mcallegari10 requested changes

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/index.html
> +        <img class="title-decoration" src="img/triangle.svg" alt="title decoration">
For images that are just for a "decoration" purpose, they are not really important semantically for our HTML structure, we use [pseudo-elements](https://developer.mozilla.org/en-US/docs/Web/CSS/Pseudo-elements). Please check that and let me know if you have any questions 😄

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/index.html
> +    <img src="img/wolox_logo.svg" alt="Wolox logo" class="nav-logo">
No need for the word `logo` in the `alt`. Keep in mind this attribute should only be a description of the image, not the actual image usage

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/index.html
> +      <img src="img/wolox_logo_white.svg" alt="wolox white logo">
Same here, no need for the logo

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/index.html
> +          <img src="img/react_icon.svg" alt="React logo" class="tech-box-logo">
Same here, check the alt attribute and remove the logo. Check the other techs! 😄

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/scss/styles.scss
> +  padding: 160px 100px 100px;
No need for this. If you want to set a space between the content and the border of the browser, you can do something like:

```scss
.main-content {
  margin: 0 auto;
  max-width: $content-size: // this content size should be something like 800px
  width: 100%:
}
```
That way, you content will be always on the center of the screen as we want it 😄

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/scss/styles.scss
> +  .tech-area:not(:last-child){
No need for this

2018-10-05 23:26 UTC, mcallegari10 commented on maquetado/scss/styles.scss
> +    margin: 20px 0 0 0;
I think this is not needed and it's solved with the code in the `main-content`

2018-10-08 11:44 UTC, Dorian30 commented on maquetado/index.html
> +        <img class="title-decoration" src="img/triangle.svg" alt="title decoration">
Ok, I understand. I'll change it to a pseudo-element.

2018-10-08 11:46 UTC, Dorian30 commented on maquetado/index.html
> +    <img src="img/wolox_logo.svg" alt="Wolox logo" class="nav-logo">
Ok. I'm on it.

2018-10-08 11:48 UTC, Dorian30 commented on maquetado/scss/styles.scss
> +  padding: 160px 100px 100px;
Perfect! I was not sure if the content was supposed to be centered in this case. I'll change it.

2018-10-08 11:56 UTC, Dorian30 commented on maquetado/scss/styles.scss
> +    margin: 20px 0 0 0;
@mcallegari10 I'm using this to make some space between the title area and the box list where all cards sit. 

![image](https://user-images.githubusercontent.com/36488701/46607459-7258c600-cad7-11e8-956f-6dad44667b9f.png)

Do I delete it anyway ?

2018-10-08 12:18 UTC, Dorian30 commented on maquetado/scss/styles.scss
> +  .tech-area:not(:last-child){
Ok. I'll delete it.

2018-10-08 14:20 UTC, mcallegari10 requested changes

2018-10-08 14:20 UTC, mcallegari10 commented on maquetado/scss/footer.scss
> +  color: white;
Change to variable please

2018-10-08 14:20 UTC, mcallegari10 commented on maquetado/scss/footer.scss
> +  color: white;
Same here

2018-10-08 14:20 UTC, mcallegari10 commented on maquetado/scss/footer.scss
> +  display: block;
I think this is not needed, check the alignment with `align-self`

2018-10-08 14:20 UTC, mcallegari10 commented on maquetado/scss/titles.scss
> +  position: relative;
If the pseudo-element has position `relative`, there's no need to add this relative 😄

2018-10-08 14:20 UTC, mcallegari10 commented on maquetado/scss/application.scss
> +$text-small: 12px;
I'd put this variables in a file like `colors` but name it `sizes`

2018-10-08 22:03 UTC, mcallegari10 approved these changes

2018-10-09 12:31 UTC, merged