Refactoring Tic Tac Toe with Redux
wolox-training/da-react pull request #10
Opened 2018-11-01 22:44 UTC by Dorian30

## Summary
- Refactored Tic Tac Toe to Redux structure. 
- Set a game reducer to handle changes made to the state of the Tic Tac Toe. 
- Defined several actions to control the events of the app.

## Screenshot
![image](https://user-images.githubusercontent.com/36488701/47884117-56aeba00-de0e-11e8-9b73-632805ba4063.png)

## Trello Card
https://trello.com/c/bm4y3a69/14-redux-i-actions-reducers-store-todo-finger

2018-11-02 18:52 UTC, LucasZibell requested changes

2018-11-02 18:52 UTC, LucasZibell commented on react-app/src/redux/game/reducer.js
> +const jumpTo = (state, step) => {
same

2018-11-02 18:52 UTC, LucasZibell commented on react-app/src/redux/game/reducer.js
> +const handleClick = (state, squarePosition) => {
Try to have all this logic in the action, the reducer should be to just update the state

2018-11-02 18:52 UTC, LucasZibell commented on react-app/src/redux/game/reducer.js
> +const jumpTo = (state, step) => {
Also, this functions are pretty big, how about moving them to gameActionUtils.js and export them from there

2018-11-02 18:52 UTC, LucasZibell commented on react-app/src/redux/game/actions.js
> +    type: actions.HANDLE_CLICK,
How about a better name? Like play turn or something like that. Keep in mind in the action you will have tons of actions, an `handleClick` is pretty generic

2018-11-02 18:52 UTC, LucasZibell commented on react-app/src/redux/game/actions.js
> +    type: actions.JUMP_TO,
same

2018-11-06 12:39 UTC, HarryPerez approved these changes

2018-11-06 12:40 UTC, LucasZibell approved these changes

2018-11-06 22:41 UTC, merged