Tic Tac Toe / Folder Structure
wolox-training/da-react pull request #7
Opened 2018-10-23 15:51 UTC by Dorian30

## Summary
- Took the base code and adapted it to the tree folder structure proposed in the card.
- Defined 3 main components with their respective styles: Board, Game and Square.
- Tested it with npm start.

## Screenshot
![image](https://user-images.githubusercontent.com/36488701/47373055-6cf7a000-d6c1-11e8-84e1-02ac5ae9fd84.png)

## Trello Card
https://trello.com/c/PMgm9D0F/32-estructura-de-carpetas

2018-10-23 16:07 UTC, LucasZibell commented
How about moving the `App` folder into a screen folder as `game` or something like this and import the components to use in that screen

2018-10-23 17:28 UTC, HarryPerez requested changes

2018-10-23 17:28 UTC, HarryPerez commented on react-app/src/scss/index.scss
> +}
Add `EOF` here. (End of file).

2018-10-23 17:28 UTC, HarryPerez commented on react-app/src/app/components/Square/styles.scss
> +}
Add `EOF` here. (End of file).

2018-10-23 17:28 UTC, HarryPerez commented on react-app/src/app/components/Board/style.scss
> +}
Add `EOF` here. (End of file).

2018-10-23 17:28 UTC, HarryPerez commented on react-app/src/app/components/Game/index.js
> +export default Game;
Game should be an screen. `Then Board...Squares and all componentes should be inside Game screen.`

2018-10-23 17:28 UTC, HarryPerez commented on react-app/src/app/components/Game/index.js
> +export default Game;
For example: `/src/app/screens/Game/components/Square/index.js`

2018-10-24 14:59 UTC, HarryPerez commented
Very good!! In this pr we will only check folder structure. In the next PR we will check the whole app

2018-10-24 15:00 UTC, HarryPerez approved these changes

2018-10-24 15:20 UTC, merged